### ISSUE TITLE
Couple of quick questions

### ISSUE THREAD

**Issue by frownbreaker** [spangenberg/kubernetes-xenserver-storage#2]
I was wondering if I could use this in a small non-production environment with a dedicated Xen(XCP-NG) environment to try out basic Kubernetes integration with GitLab CE. I understand the concern about the shared credentials being needed but for my use case, this is not a concern.

Specifically, I want to ask the pros/cons of using this toolchain which I understand leverages Xen's VM capabilities Vs Running a more typical Kubernetes setup. The reason I'm asking is I like the Xen server operations and management via XCP-NG and GitLab CE works very well for our development. It would be nice at some point to use the automated pipelines in GitLab CE that require a Kubernetes cluster which is why I wanted to look at this project.

**Comment by spangenberg** [comment]
I'm not sure if I totally understand your question.
This project focuses on how to leverage Xen's or XCP-ng's Storage Pool to enable persistent volumes in Kubernetes.
It requires an already running Kubernetes on your Xen cluster.

Maybe what you're looking for is https://github.com/kubernetes-sigs/cluster-api, but there is no Xen integration I'm aware of at the moment.

**Comment by frownbreaker** [comment]
Ah Ok. Thanks for the reply.

- I have a Xen host for VMs. One of my VMs is GitLab.
- I understand that GitLabs continuous integration supports Kubernetes.
- From what you are saying I need to install Kubernetes instance on a VM on my Xen host (I'm using XCP-NG) then I'll have an operational Kubernetes on my Xen server that I can link up with the GitLab CE instance running on Debian on a VM on my Xen host.

I thought your project would let me host Kubernetes on Xen but it looks like its some kind of storage provisions for Kubernetes that runs on Xen?

Hope I got that right this time. I'm new to this appreciate your patience!

**Comment by spangenberg** [comment]
Hi, yes exactly this project just focuses on supporting XenServer/XCP-ng volume management for Kubernetes/OpenShift.
It doesn't help you setting up a cluster.

But about the problem you're trying to solve... do you plan on having a kubernetes deploying things or do you just want to leverage XCP-ng as a dynamic build platform.
If so you can skip all of the kubernetes and just use the gitlab-runner together with the docker-machine platform. There is a plugin for it which allows gitlab-runner to boot VM's to distribute the workload. You can find it here: https://github.com/xenserver/docker-machine-driver-xenserver

I also created a docker image which does exactly that, didn't yet push the code but you can find it here, maybe that's what you're looking for: https://hub.docker.com/r/spangenberg/gitlab-xenserver-runner
